const data = [
  {
    Id: "1",
    Name: "Bat",
    Availability: 10,
    Price: 500,
    URL: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcThK16DJse26jntYK8HeR3dASGqD2Vr7abeRA&usqp=CAU",
    Description: "THIS IS A HEAVY BAT",
  },
  {
    Id: "2",
    Name: "Ball",
    Availability: 12,
    Price: 200,
    URL: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcThK16DJse26jntYK8HeR3dASGqD2Vr7abeRA&usqp=CAU",
    Description: "THIS IS A HEAVY BALL",
  },
  {
    Id: "3",
    Name: "Stumps",
    Availability: 13,
    Price: 200,
    URL: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcThK16DJse26jntYK8HeR3dASGqD2Vr7abeRA&usqp=CAU",
    Description: "THIS IS A HEAVY STUMPS",
  },
  {
    Id: "4",
    Name: "Gloves",
    Availability: 15,
    Price: 100,
    URL: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcThK16DJse26jntYK8HeR3dASGqD2Vr7abeRA&usqp=CAU",
    Description: "THIS IS A HEAVY GLOVES",
  },
  {
    Id: "5",
    Name: "Helmet",
    Availability: 20,
    Price: 600,
    URL: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcThK16DJse26jntYK8HeR3dASGqD2Vr7abeRA&usqp=CAU",
    Description: "THIS IS A HEAVY HELMET",
  },
  {
    Id: "6",
    Name: "Pads",
    Availability: 16,
    Price: 50,
    URL: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcThK16DJse26jntYK8HeR3dASGqD2Vr7abeRA&usqp=CAU",
    Description: "THIS IS A HEAVY PAD",
  },
  {
    Id: "7",
    Name: "Shoes",
    Availability: 50,
    Price: 250,
    URL: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcThK16DJse26jntYK8HeR3dASGqD2Vr7abeRA&usqp=CAU",
    Description: "THIS IS A HEAVY SHOES",
  },
];

export default data;
