const data = [
  {
    id: "1",
    name: "MRF Bat",
    availability: 10,
    category: "Bat",
    price: 500,
    url: "/Bat.png",
    shortDesc: "MRF Bat with Grip",
  },
  {
    id: "2",
    name: "Kookabura Ball",
    category: "Ball",
    availability: 12,
    price: 200,
    url: "/Ball.png",
    shortDesc: "Kookabura red Ball",
  },
  {
    id: "3",
    name: "BoldFit Stumps",
    availability: 13,
    category: "Stumps",
    price: 200,
    url: "/Stumps.png",
    shortDesc: "BoldFit Stumps with Bails",
  },
  {
    id: "4",
    name: "SG Wicket Keeping Gloves",
    category: "Gloves",
    availability: 15,
    price: 100,
    url: "/Gloves.png",
    shortDesc: "SG WicketKeeping Gloves with inners",
  },
  {
    id: "5",
    name: "DSC Helmet",
    category: "Helmet",
    availability: 20,
    price: 600,
    url: "/Helmet.png",
    shortDesc: "DSC Helmet with inner protection",
  },
  {
    id: "6",
    name: "RK Pads",
    category: "Pads",
    availability: 16,
    price: 50,
    url: "/Pads.png",
    shortDesc: "RK cushion gloves",
  },
  {
    id: "7",
    name: "Adidas Shoes",
    availability: 50,
    category: "Shoes",
    price: 250,
    url: "/Shoes.png",
    shortDesc: "Adidas Running Shoes",
  },
];

export default data;
