const data = [
  {
    Id: "1",
    Name: "MRF Bat",
    Availability: 10,
    Price: 500,
    URL: "/Bat.png",
    Description: "THIS IS A HEAVY BAT",
  },
  {
    Id: "2",
    Name: "Kookabura Ball",
    Availability: 12,
    Price: 200,
    URL: "/Ball.png",
    Description: "THIS IS A HEAVY BALL",
  },
  {
    Id: "3",
    Name: "Stumps",
    Availability: 13,
    Price: 200,
    URL: "/Stumps.png",
    Description: "THIS IS A HEAVY STUMPS",
  },
  {
    Id: "4",
    Name: "SG Wicket Keeping Gloves",
    Availability: 15,
    Price: 100,
    URL: "/Gloves.png",
    Description: "THIS IS A HEAVY GLOVES",
  },
  {
    Id: "5",
    Name: "DSC Helmet",
    Availability: 20,
    Price: 600,
    URL: "/Helmet.png",
    Description: "THIS IS A HEAVY HELMET",
  },
  {
    Id: "6",
    Name: "RK Pads",
    Availability: 16,
    Price: 50,
    URL: "/Pads.png",
    Description: "THIS IS A HEAVY PAD",
  },
  {
    Id: "7",
    Name: "Adidas Shoes",
    Availability: 50,
    Price: 250,
    URL: "/Shoes.png",
    Description: "THIS IS A HEAVY SHOES",
  },
];

export default data;
